/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 检查服务是否正常运行
         */
        get: operations["health.check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取会话列表
         * @description 获取所有会话的列表
         */
        get: operations["sessions.list"];
        put?: never;
        /**
         * 创建新会话
         * @description 创建一个新的聊天会话
         */
        post: operations["sessions.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取会话详情
         * @description 根据 ID 获取会话的详细信息，包括消息历史
         */
        get: operations["sessions.get"];
        /**
         * 重命名会话
         * @description 修改会话名称
         */
        put: operations["sessions.rename"];
        post?: never;
        /**
         * 删除会话
         * @description 根据 ID 删除指定会话
         */
        delete: operations["sessions.delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加消息到会话
         * @description 向指定会话添加一条消息
         */
        post: operations["sessions.messages.add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 会话聊天
         * @description 在指定会话中进行聊天，返回 AI 响应
         */
        post: operations["sessions.chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 会话流式聊天
         * @description 在指定会话中进行流式聊天，实时返回 AI 响应
         */
        post: operations["sessions.chat.stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 无会话聊天
         * @description 直接发送消息进行聊天，不需要会话
         */
        post: operations["chat.send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 无会话流式聊天
         * @description 直接发送消息进行流式聊天，不需要会话
         */
        post: operations["chat.stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "health.check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务健康状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 服务状态 */
                        status: string;
                        /** @description 当前使用的模型 */
                        model: string;
                    };
                };
            };
        };
    };
    "sessions.list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 会话列表 */
                        sessions: {
                            /** @description 会话 ID */
                            id: string;
                            /** @description 会话名称 */
                            name: string;
                            /** @description 创建时间 */
                            createdAt: string;
                            /** @description 更新时间 */
                            updatedAt: string;
                            /** @description 消息数量 */
                            messageCount: number;
                        }[];
                    };
                };
            };
        };
    };
    "sessions.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 会话名称 */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description 创建的会话 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 创建的会话 */
                        session: {
                            /** @description 会话 ID */
                            id: string;
                            /** @description 会话名称 */
                            name: string;
                            /** @description 创建时间 */
                            createdAt: string;
                            /** @description 更新时间 */
                            updatedAt: string;
                            /** @description 消息数量 */
                            messageCount: number;
                        };
                    };
                };
            };
        };
    };
    "sessions.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 会话详情 */
                        session: {
                            /** @description 会话 ID */
                            id: string;
                            /** @description 会话名称 */
                            name: string;
                            /** @description 创建时间 */
                            createdAt: string;
                            /** @description 更新时间 */
                            updatedAt: string;
                            /** @description 消息数量 */
                            messageCount: number;
                            /** @description 消息列表 */
                            messages: {
                                /**
                                 * @description 消息角色
                                 * @enum {string}
                                 */
                                role: "user" | "assistant" | "system";
                                /** @description 消息内容 */
                                content: string;
                                /** @description 消息时间 */
                                timestamp: string;
                            }[];
                        };
                    };
                };
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "sessions.rename": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 新会话名称 */
                    name: string;
                };
            };
        };
        responses: {
            /** @description 重命名成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 操作是否成功 */
                        success: boolean;
                    };
                };
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "sessions.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 操作是否成功 */
                        success: boolean;
                    };
                };
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "sessions.messages.add": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 消息角色
                     * @enum {string}
                     */
                    role: "user" | "assistant" | "system";
                    /** @description 消息内容 */
                    content: string;
                };
            };
        };
        responses: {
            /** @description 添加成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 操作是否成功 */
                        success: boolean;
                    };
                };
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "sessions.chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 用户消息 */
                    message: string;
                };
            };
        };
        responses: {
            /** @description 聊天响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description AI 响应 */
                        response: string;
                        /** @description Token 使用情况 */
                        usage?: {
                            /** @description 输入 token 数 */
                            promptTokens: number;
                            /** @description 输出 token 数 */
                            completionTokens: number;
                            /** @description 总 token 数 */
                            totalTokens: number;
                        };
                    };
                };
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
            /** @description 服务器错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "sessions.chat.stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 用户消息 */
                    message: string;
                };
            };
        };
        responses: {
            /** @description 流式响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "chat.send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 消息历史 */
                    messages: {
                        /**
                         * @description 消息角色
                         * @enum {string}
                         */
                        role: "user" | "assistant" | "system";
                        /** @description 消息内容 */
                        content: string;
                        /** @description 消息时间 */
                        timestamp: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description 聊天响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description AI 响应 */
                        response: string;
                        /** @description Token 使用情况 */
                        usage?: {
                            /** @description 输入 token 数 */
                            promptTokens: number;
                            /** @description 输出 token 数 */
                            completionTokens: number;
                            /** @description 总 token 数 */
                            totalTokens: number;
                        };
                    };
                };
            };
            /** @description 服务器错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
    "chat.stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 消息历史 */
                    messages: {
                        /**
                         * @description 消息角色
                         * @enum {string}
                         */
                        role: "user" | "assistant" | "system";
                        /** @description 消息内容 */
                        content: string;
                        /** @description 消息时间 */
                        timestamp: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description 流式响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 服务器错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 错误信息 */
                        error: string;
                    };
                };
            };
        };
    };
}
