// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AgentAbortData, AgentAbortResponses, ChatSendData, ChatSendErrors, ChatSendResponses, ChatStreamData, ChatStreamErrors, ChatStreamResponses, HealthCheckData, HealthCheckResponses, SessionsChatSendData, SessionsChatSendErrors, SessionsChatSendResponses, SessionsChatStreamData, SessionsChatStreamErrors, SessionsChatStreamResponses, SessionsCreateData, SessionsCreateResponses, SessionsDeleteData, SessionsDeleteErrors, SessionsDeleteResponses, SessionsForkData, SessionsForkErrors, SessionsForkResponses, SessionsGetData, SessionsGetErrors, SessionsGetResponses, SessionsListData, SessionsListResponses, SessionsMessagesAddData, SessionsMessagesAddErrors, SessionsMessagesAddResponses, SessionsRenameData, SessionsRenameErrors, SessionsRenameResponses, SessionsResumeData, SessionsResumeErrors, SessionsResumeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 健康检查
 *
 * 检查服务是否正常运行
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * 获取会话列表
 *
 * 获取所有会话的列表
 */
export const sessionsList = <ThrowOnError extends boolean = false>(options?: Options<SessionsListData, ThrowOnError>) => (options?.client ?? client).get<SessionsListResponses, unknown, ThrowOnError>({ url: '/sessions', ...options });

/**
 * 创建新会话
 *
 * 创建一个新的聊天会话
 */
export const sessionsCreate = <ThrowOnError extends boolean = false>(options: Options<SessionsCreateData, ThrowOnError>) => (options.client ?? client).post<SessionsCreateResponses, unknown, ThrowOnError>({
    url: '/sessions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除会话
 *
 * 根据 ID 删除指定会话
 */
export const sessionsDelete = <ThrowOnError extends boolean = false>(options: Options<SessionsDeleteData, ThrowOnError>) => (options.client ?? client).delete<SessionsDeleteResponses, SessionsDeleteErrors, ThrowOnError>({ url: '/sessions/{id}', ...options });

/**
 * 获取会话详情
 *
 * 根据 ID 获取会话的详细信息，包括消息历史
 */
export const sessionsGet = <ThrowOnError extends boolean = false>(options: Options<SessionsGetData, ThrowOnError>) => (options.client ?? client).get<SessionsGetResponses, SessionsGetErrors, ThrowOnError>({ url: '/sessions/{id}', ...options });

/**
 * 重命名会话
 *
 * 修改会话名称
 */
export const sessionsRename = <ThrowOnError extends boolean = false>(options: Options<SessionsRenameData, ThrowOnError>) => (options.client ?? client).put<SessionsRenameResponses, SessionsRenameErrors, ThrowOnError>({
    url: '/sessions/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fork 会话
 *
 * 从指定消息的某个位置创建一个新会话，保留该位置之前的所有消息
 */
export const sessionsFork = <ThrowOnError extends boolean = false>(options: Options<SessionsForkData, ThrowOnError>) => (options.client ?? client).post<SessionsForkResponses, SessionsForkErrors, ThrowOnError>({
    url: '/sessions/{id}/fork',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Resume 会话
 *
 * 在指定消息位置之后恢复对话，截断该消息之后的所有消息
 */
export const sessionsResume = <ThrowOnError extends boolean = false>(options: Options<SessionsResumeData, ThrowOnError>) => (options.client ?? client).post<SessionsResumeResponses, SessionsResumeErrors, ThrowOnError>({
    url: '/sessions/{id}/resume',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 添加消息到会话
 *
 * 向指定会话添加一条消息
 */
export const sessionsMessagesAdd = <ThrowOnError extends boolean = false>(options: Options<SessionsMessagesAddData, ThrowOnError>) => (options.client ?? client).post<SessionsMessagesAddResponses, SessionsMessagesAddErrors, ThrowOnError>({
    url: '/sessions/{id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Agent 对话
 *
 * 使用 Agent 模式进行对话，支持工具调用和 ReAct 循环，返回 SSE 事件流
 */
export const sessionsChatSend = <ThrowOnError extends boolean = false>(options: Options<SessionsChatSendData, ThrowOnError>) => (options.client ?? client).sse.post<SessionsChatSendResponses, SessionsChatSendErrors, ThrowOnError>({
    url: '/sessions/{id}/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 会话流式聊天
 *
 * 在指定会话中进行流式聊天，实时返回 AI 响应
 */
export const sessionsChatStream = <ThrowOnError extends boolean = false>(options: Options<SessionsChatStreamData, ThrowOnError>) => (options.client ?? client).post<SessionsChatStreamResponses, SessionsChatStreamErrors, ThrowOnError>({
    url: '/sessions/{id}/chat/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 无会话聊天
 *
 * 直接发送消息进行聊天，不需要会话
 */
export const chatSend = <ThrowOnError extends boolean = false>(options: Options<ChatSendData, ThrowOnError>) => (options.client ?? client).post<ChatSendResponses, ChatSendErrors, ThrowOnError>({
    url: '/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 无会话流式聊天
 *
 * 直接发送消息进行流式聊天，不需要会话
 */
export const chatStream = <ThrowOnError extends boolean = false>(options: Options<ChatStreamData, ThrowOnError>) => (options.client ?? client).post<ChatStreamResponses, ChatStreamErrors, ThrowOnError>({
    url: '/chat/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 终止 Agent 运行
 *
 * 终止当前正在运行的 Agent
 */
export const agentAbort = <ThrowOnError extends boolean = false>(options: Options<AgentAbortData, ThrowOnError>) => (options.client ?? client).post<AgentAbortResponses, unknown, ThrowOnError>({
    url: '/sessions/{id}/agent/abort',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
