// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type SessionsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type SessionsListResponses = {
    /**
     * 会话列表
     */
    200: {
        /**
         * 会话列表
         */
        sessions: Array<{
            /**
             * 会话 ID
             */
            id: string;
            /**
             * 会话名称
             */
            name: string;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            /**
             * 消息数量
             */
            messageCount: number;
        }>;
    };
};

export type SessionsListResponse = SessionsListResponses[keyof SessionsListResponses];

export type SessionsCreateData = {
    body: {
        /**
         * 会话名称
         */
        name?: string;
    };
    path?: never;
    query?: never;
    url: '/sessions';
};

export type SessionsCreateResponses = {
    /**
     * 创建的会话
     */
    201: {
        /**
         * 创建的会话
         */
        session: {
            /**
             * 会话 ID
             */
            id: string;
            /**
             * 会话名称
             */
            name: string;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            /**
             * 消息数量
             */
            messageCount: number;
        };
    };
};

export type SessionsCreateResponse = SessionsCreateResponses[keyof SessionsCreateResponses];

export type SessionsDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type SessionsDeleteErrors = {
    /**
     * 会话不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsDeleteError = SessionsDeleteErrors[keyof SessionsDeleteErrors];

export type SessionsDeleteResponses = {
    /**
     * 删除成功
     */
    200: {
        /**
         * 操作是否成功
         */
        success: boolean;
    };
};

export type SessionsDeleteResponse = SessionsDeleteResponses[keyof SessionsDeleteResponses];

export type SessionsGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type SessionsGetErrors = {
    /**
     * 会话不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsGetError = SessionsGetErrors[keyof SessionsGetErrors];

export type SessionsGetResponses = {
    /**
     * 会话详情
     */
    200: {
        /**
         * 会话详情
         */
        session: {
            /**
             * 会话 ID
             */
            id: string;
            /**
             * 会话名称
             */
            name: string;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            /**
             * 消息数量
             */
            messageCount: number;
            /**
             * 消息列表
             */
            messages: Array<{
                /**
                 * 消息 ID
                 */
                id: string;
                /**
                 * 消息角色
                 */
                role: 'user' | 'assistant' | 'system';
                /**
                 * 消息内容
                 */
                content: string;
                /**
                 * 消息时间
                 */
                timestamp: string;
            }>;
        };
    };
};

export type SessionsGetResponse = SessionsGetResponses[keyof SessionsGetResponses];

export type SessionsRenameData = {
    body: {
        /**
         * 新会话名称
         */
        name: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type SessionsRenameErrors = {
    /**
     * 会话不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsRenameError = SessionsRenameErrors[keyof SessionsRenameErrors];

export type SessionsRenameResponses = {
    /**
     * 重命名成功
     */
    200: {
        /**
         * 操作是否成功
         */
        success: boolean;
    };
};

export type SessionsRenameResponse = SessionsRenameResponses[keyof SessionsRenameResponses];

export type SessionsForkData = {
    body: {
        /**
         * 消息 ID
         */
        messageId: string;
        /**
         * 新会话名称
         */
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/fork';
};

export type SessionsForkErrors = {
    /**
     * 会话或消息不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsForkError = SessionsForkErrors[keyof SessionsForkErrors];

export type SessionsForkResponses = {
    /**
     * Fork 成功
     */
    201: {
        /**
         * 新创建的会话
         */
        session: {
            /**
             * 会话 ID
             */
            id: string;
            /**
             * 会话名称
             */
            name: string;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            /**
             * 消息数量
             */
            messageCount: number;
        };
    };
};

export type SessionsForkResponse = SessionsForkResponses[keyof SessionsForkResponses];

export type SessionsResumeData = {
    body: {
        /**
         * 消息 ID
         */
        messageId: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/resume';
};

export type SessionsResumeErrors = {
    /**
     * 会话或消息不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsResumeError = SessionsResumeErrors[keyof SessionsResumeErrors];

export type SessionsResumeResponses = {
    /**
     * Resume 成功
     */
    200: {
        /**
         * 操作是否成功
         */
        success: boolean;
    };
};

export type SessionsResumeResponse = SessionsResumeResponses[keyof SessionsResumeResponses];

export type SessionsMessagesAddData = {
    body: {
        /**
         * 消息角色
         */
        role: 'user' | 'assistant' | 'system';
        /**
         * 消息内容
         */
        content: string;
        /**
         * 消息时间
         */
        timestamp?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/messages';
};

export type SessionsMessagesAddErrors = {
    /**
     * 会话不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsMessagesAddError = SessionsMessagesAddErrors[keyof SessionsMessagesAddErrors];

export type SessionsMessagesAddResponses = {
    /**
     * 添加成功
     */
    200: {
        /**
         * 操作是否成功
         */
        success: boolean;
    };
};

export type SessionsMessagesAddResponse = SessionsMessagesAddResponses[keyof SessionsMessagesAddResponses];

export type SessionsChatSendData = {
    body: {
        /**
         * 用户消息
         */
        message: string;
        /**
         * 启用的工具列表
         */
        enabledTools?: Array<string>;
        /**
         * 最大迭代次数
         */
        maxIterations?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/chat';
};

export type SessionsChatSendErrors = {
    /**
     * 会话不存在
     */
    404: {
        /**
         * 错误信息
         */
        error: string;
    };
    /**
     * 服务器错误
     */
    500: {
        /**
         * 错误信息
         */
        error: string;
    };
};

export type SessionsChatSendError = SessionsChatSendErrors[keyof SessionsChatSendErrors];

export type SessionsChatSendResponses = {
    /**
     * SSE 事件流
     */
    200: {
        /**
         * 事件类型
         */
        event: string;
        /**
         * 事件数据 JSON
         */
        data: string;
    };
};

export type SessionsChatSendResponse = SessionsChatSendResponses[keyof SessionsChatSendResponses];

export type AgentAbortData = {
    body: {
        /**
         * 要终止的运行 ID
         */
        run_id: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}/agent/abort';
};

export type AgentAbortResponses = {
    /**
     * 终止成功
     */
    200: {
        /**
         * 是否成功
         */
        success: boolean;
    };
};

export type AgentAbortResponse = AgentAbortResponses[keyof AgentAbortResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system/health';
};

export type HealthCheckResponses = {
    /**
     * 服务健康状态
     */
    200: {
        /**
         * 服务状态
         */
        status: string;
        /**
         * 当前使用的模型
         */
        model: string;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
